# Generated by Django 4.2 on 2023-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('body', models.TextField()),
                ('soluong', models.FloatField()),
                ('giaca', models.FloatField()),
            ],
        ),
    ]
